StudentMarkManagement/Models/ErrorViewModel.cs
using System;

namespace StudentMarkManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentMarkManagement/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentMarkManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StudentMarkManagement.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentMarkManagement/Controllers/StudentMarkManagementController.cs
using Microsoft.AspNetCore.Mvc;
using StudentMarkManagement.Core;
using StudentMarkManagement.Core.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentMarkManagement.Controllers
{
    public class StudentMarkManagementController : Controller
    {
        readonly IStudentMarkServices _studentMarkServices;
        public StudentMarkManagementController(IStudentMarkServices studentMarkServices)
        {
            _studentMarkServices = studentMarkServices;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DashBoard()
        {
            StudentDetails stdDetails = new StudentDetails();
            stdDetails.Department = _studentMarkServices.GetAllDepartment();
            return View(stdDetails);
        }

        public IActionResult MarkDashBoard()
        {
            StudentDetails stdDetails = new StudentDetails();
            stdDetails.Department = _studentMarkServices.GetAllDepartment();
            return View(stdDetails);
        }


        public IActionResult ViewStudentDetails(StudentDetails stdDetails)
        {

            var list = _studentMarkServices.ViewStudentDetails(stdDetails);
            return View(list);
        }
        [HttpPost]
        public IActionResult SaveStudentDetails(StudentDetails stdDetails)
        {

            _studentMarkServices.SaveStudentDetails(stdDetails);
            return RedirectToAction("ViewStudentDetails");
        }
        public IActionResult DeleteStudentDetails(int id)
        {
            _studentMarkServices.DeleteStudentDetails(id);
            return RedirectToAction("ViewStudentDetails");
        }
    }
}

StudentMarkManagement/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StudentMarkManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentMarkManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentMarkManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StudentMarkManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentMarkManagement/Views/StudentMarkManagement/DashBoard.cshtml
@model StudentMarkManagement.Core.Model.StudentDetails

<h1>Student Details</h1>
@using (Html.BeginForm("SaveStudentDetails", "StudentMarkManagement", FormMethod.Post, new { @id = "Formdetails" }))
{

    <style>
        span {
            color: red;
        }
    </style>
    @Html.HiddenFor(x => x.StudentId)
    <div class="container">

        <div class="form-group">
            @*@Html.LabelFor(x => x.StudentName, new { @class = "form-label" })*@
            <label class="col-form-label"> Enter Your Name</label><span>*</span>
            @Html.TextBoxFor(x => x.StudentName, new { @class = "form-control", @placeholder = "Enter Your Name" })
        </div>

        <div class="form-group">
            <label class="col-form-label"> Enter Your Email Address</label><span>*</span>

            @Html.TextBoxFor(x => x.StudentEmail, new { @class = "form-control", @placeholder = "Enter Your Email" })
        </div>

        <div class="form-group">
            @*@Html.LabelFor(x => x.StudentDepartment, new { @class = "form-label" })*@
            <label class="col-form-label">Department</label><span>*</span>
            @Html.DropDownList("StudentDepartment", new SelectList(Model.Department, "DepartmentId", "DepartmentName"), "Select Department", new { id = "StudentDepartment", @style = "width:210px" })
            @*@Html.DropDownListFor(x => x.StudentDepartment, new List<SelectListItem> { new SelectListItem() { Text = "---Select Department---", Value = "" },
                new SelectListItem { Text="Java", Value="Java"} })*@

        </div>



        <div class="form-group">
            @*@Html.LabelFor(x => x.Gender, new { @class = "form-label" })*@
            <label class="col-form-label"> Gender</label><span>*</span>
            @*@Html.RadioButtonFor(x => x.Gender, new { @class = "form-control" })*@
            @Html.RadioButtonFor(x => x.Gender, "Male")Male
            @Html.RadioButtonFor(x => x.Gender, "Female")Female
        </div>



        <div class="form-group">
            <button type="submit" class="btn btn-primary" onclick="SubmitDetails()">Submit</button>
        </div>
        @ViewBag.Message
            <environment include="Development">
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
                <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
            </environment>
    </div>
}
<script>


    $(function () {
        $("#Formdetails").validate({
            rules: {
                Enter Your Name:
                {
                    required: true
                },
                Enter Your Email Address:
                {
                    required: true,
                },
                Department:
                {
                    required: true
                },
                Gender:
                {
                    required: true
                }
            },
            messages:
            {
                Enter Your Name:
                {
                    required: "Name is required",
                },
                Enter Your Email Address:
                {
                    required: "Last is required",
                },
                Department:
                {
                    required: "required"
                },
                Gender:
                {
                    required: "student age is required"
                }
               
            }
        });
    });
    function SubmitDetails() {
        if ($("#Formdetails").validate()) {
            $("#Formdetails").submit();
        }
    }
  
</script>

StudentMarkManagement/Views/StudentMarkManagement/MarkDashBoard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model StudentMarkManagement.Core.Model.StudentMarkDetails

<h1>Student Mark Details</h1>
@using (Html.BeginForm("SaveStudentDetails", "StudentMarkManagement", FormMethod.Post, new { @id = "Formdetails" }))
{

    <style>
        span {
            color: red;
        }
    </style>
    @Html.HiddenFor(x => x.StuduentId)
<div class="container">

    <div class="form-group">
        @*@Html.LabelFor(x => x.StudentName, new { @class = "form-label" })*@
        <label class="col-form-label"> Enter Your Name</label><span>*</span>
        @Html.TextBoxFor(x => x.StuduentName, new { @class = "form-control", @placeholder = "Enter Your Name" })
    </div>

    <div class="form-group">
        <label class="col-form-label"> Mark 1</label><span>*</span>

        @Html.TextBoxFor(x => x.Mark1, new { @class = "form-control", @placeholder = "Enter Your Email" })
    </div>


    <div class="form-group">
        <label class="col-form-label"> Mark 2</label><span>*</span>

        @Html.TextBoxFor(x => x.Mark2, new { @class = "form-control", @placeholder = "Enter Your Email" })
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary" onclick="SubmitDetails()">Submit</button>
    </div>
    @*@ViewBag.Message
        <environment include="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
            <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
        </environment>*@
</div>
}

StudentMarkManagement/Views/StudentMarkManagement/ViewStudentDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<StudentMarkManagement.Core.Model.StudentDetails>
<div class="container">
    
    <table class="table table-hover">

        <tr>

            <th>S.No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department Name</th>
            <th>Gender</th>
            <th>Action</th>

        </tr>


        @foreach (var item in Model)
        {
            <tr>


                <td> @item.StudentId </td>
                <td> @item.StudentName </td>
                <td>@item.StudentEmail</td>
                <td> @item.StudentDepartment </td>
                <td> @item.Gender</td>
                <td>

                    <i class="glyphicon glyphicon-trash">@Html.ActionLink("Delete", "DeleteStudentDetails", new { id = item.StudentId }, new { onclick = "return confirm('Are sure wants to delete?');" })

                </td>

            </tr>
        }
    </table>
</div>
    